import trolley from "../images/trolley.png";
import redHeart from "../images/redHeart.png";
import image1 from "@/images/Pizza1.png";
import image2 from "@/images/Pizza2.png";
import image3 from "@/images/Pizza3.png";
import image4 from "@/images/Pizza4.png";
import image5 from "@/images/Pizza5.png";
import image6 from "@/images/Pizza6.png";

export interface Pizza {
    title: string,
    isNew: boolean,
    newPrice: string,
    priceNew: string,
    priceOld: string,
    oldPrice: string,
    description:string,
    imageInternet: string,
    image: string,
    trolley: string,
    redHeart: string,
    buy: string,
    nw: string,
}

export interface Apartment {
    name: string;
    image: string;
    price: number;
}

const APARTMENT_DATA: Apartment[] = [
    {
        name: 'Cozy Apartment',
        image:
            'https://images.pexels.com/photos/565324/pexels-photo-565324.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        price: 1200,
    },
    {
        name: 'Modern Loft',
        image: 'https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg',
        price: 1500,
    },
    {
        name: 'Urban Studio',
        image: 'https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg',
        price: 1000,
    },
    {
        name: 'Luxury Penthouse',
        image:
            'https://images.pexels.com/photos/681331/pexels-photo-681331.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        price: 2500,
    },
    {
        name: 'Charming Condo',
        image:
            'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        price: 900,
    },
];

const PIZZA_DATA: Pizza[] = [
    {
        title: 'Pizza 1',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '30 uah',
        priceOld: '50 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image1,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "NEW",
    },
    {
        title: 'Pizza 2',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '35 uah',
        priceOld: '55 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image2,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "TOP",
    },
    {
        title: 'Pizza 3',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '33 uah',
        priceOld: '53 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image3,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "BEST",
    },
    {
        title: 'Pizza 4',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '34 uah',
        priceOld: '54 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image4,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "NEW",
    },
    {
        title: 'Pizza 5',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '45 uah',
        priceOld: '75 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image5,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "TOP",
    },
    {
        title: 'Pizza 6',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '36 uah',
        priceOld: '56 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image6,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "BEST",
    },
    {
        title: 'Pizza 7',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '45 uah',
        priceOld: '65 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image1,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "NEW",
    },
    {
        title: 'Pizza 8',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '38 uah',
        priceOld: '58 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image2,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "TOP",
    },
    {
        title: 'Pizza 9',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '37 uah',
        priceOld: '57 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image3,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "GOOD",
    },
    {
        title: 'Pizza 10',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '33 uah',
        priceOld: '53 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image4,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "NEW",
    },
    {
        title: 'Pizza 11',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '45 uah',
        priceOld: '75 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image5,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "TOP",
    },
    {
        title: 'Pizza 12',
        isNew: true,
        newPrice: 'New Price',
        priceNew: '36 uah',
        priceOld: '56 uah',
        oldPrice: 'Old Price',
        description:'Long title long title long title long title',
        imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
        image: image6,
        trolley: trolley,
        redHeart: redHeart,
        buy: "Buy",
        nw: "BEST",
    },
]



export { APARTMENT_DATA,PIZZA_DATA};