import image from "../images/Pizza1.png";
import trolley from "../images/trolley.png";
import redHeart from "../images/redHeart.png";

const mockItemData1 = {
    title: 'Pizza 1',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '30 uah',
    priceOld: '50 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "NEW",
};
const mockItemData2 = {
    title: 'Pizza 2',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '35 uah',
    priceOld: '55 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "TOP",
};
const mockItemData3 = {
    title: 'Pizza 3',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '33 uah',
    priceOld: '53 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "BEST",
};
const mockItemData4 = {
    title: 'Pizza 4',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '34 uah',
    priceOld: '54 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "NEW",
};
const mockItemData5 = {
    title: 'Pizza 5',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '45 uah',
    priceOld: '75 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "TOP",
};
const mockItemData6 = {
    title: 'Pizza 6',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '36 uah',
    priceOld: '56 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "BEST",
};
const mockItemData7 = {
    title: 'Pizza 7',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '45 uah',
    priceOld: '65 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "NEW",
};
const mockItemData8 = {
    title: 'Pizza 8',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '38 uah',
    priceOld: '58 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "TOP",
};
const mockItemData9 = {
    title: 'Pizza 9',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '37 uah',
    priceOld: '57 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "",
};
const mockItemData10 = {
    title: 'Pizza 10',
    isNew: true,
    newPrice: 'New Price',
    priceNew: '33 uah',
    priceOld: '53 uah',
    oldPrice: 'Old Price',
    description:'Long title long title long title long title',
    imageInternet: 'https://img.freepik.com/free-photo/top-view-pepperoni-pizza-with-mushroom-sausages-bell-pepper-olive-corn-black-wooden_141793-2158.jpg',
    image: image,
    trolley: trolley,
    redHeart: redHeart,
    buy: "Buy",
    new: "NEW",
};

const data = [
    { id: '1', name: 'PIZZA 1', property1: true, property2: false,property3: false,property4: false, mockItemData:mockItemData1 },
    { id: '2', name: 'PIZZA 2', property1: false, property2: true,property3: false,property4: false,mockItemData:mockItemData2 },
    { id: '3', name: 'PIZZA 3', property1: true, property2: true, property3: true, property4: true,mockItemData:mockItemData3 },
    { id: '4', name: 'PIZZA 4', property1: false, property2: false, property3: true, property4: true,mockItemData:mockItemData4 },
    { id: '5', name: 'PIZZA 5', property1: false, property2: false, property3: true, property4: true,mockItemData:mockItemData5 },
    { id: '6', name: 'PIZZA 6', property1: false, property2: false, property3: true, property4: true,mockItemData:mockItemData6 },
    { id: '7', name: 'PIZZA 7', property1: false, property2: false, property3: true, property4: true,mockItemData:mockItemData7 },
    { id: '8', name: 'PIZZA 8', property1: false, property2: false, property3: true, property4: true,mockItemData:mockItemData8 },
    { id: '9', name: 'PIZZA 9', property1: false, property2: false, property3: true, property4: true,mockItemData:mockItemData9 },
    { id: '10', name: 'PIZZA 10', property1: false, property2: false, property3: true, property4: true,mockItemData:mockItemData10 },
];
export {mockItemData1,mockItemData2,mockItemData3,mockItemData4,mockItemData5,
mockItemData6,mockItemData7,mockItemData8,mockItemData9,mockItemData10,data}